Tutorial update
pdidev/tutorial pull request #10
Opened 2024-10-30 14:12 UTC by jmorice91

In this new tutorial, we have added user_plugin and set_value plugin. We try to create a new tutorial which take account the tutorial created by Yushan in 2024 and the initial tutorial.

2024-10-30 14:31 UTC, benoitmartin88 commented on ex_deisa/CMakeLists.txt
> +set(PDI_INSTALL_PATH "/gpfs/workdir/shared/pdi-deisa/spack/opt/spack/linux-centos7-cascadelake/gcc-11.2.0/pdi-1.6.0-ethkhjdusbqvy6zfc6egdue4ao65r3zx")
This should not be a hard path.

2024-10-31 16:09 UTC, jmorice91 reviewed
The log file for exercise 2 and  6 will be added in a new commit.
I need to add also the .h5dump file.

For my side, I need some feedback about the contains of the different exercise for the README.md.  It is for this reason I don't give these file before.

2024-11-04 10:41 UTC, jmorice91 commented
Exercise 1: 
Yushan have proposed  in this exercise
- An introduction to paraconf, read the ex1.yml ( perhaps is corresponding to exercise 0  see CMakeLists.txt) 
- The user need to  add PDI_init and PDI_finalize in ex1.c. => this reason why we have reference of pdi for exercise1 : YAML file, C file and CmakeLists.txt.

If PDI is linked with paraconf to read the configuration file, I think the first point must be added in the next tutorial.

2024-11-04 10:46 UTC, jmorice91 commented
exercise 2; 
I put the log in the repository. I maintain the "trace plugin" with the following option (initial tutorial):
```yaml
  logging: { pattern: '[PDI][%n-plugin] *** %l: %v' }
```
In the documentation, there is no example with keyword logging for the Trace plugin !

2024-11-04 15:50 UTC, jmorice91 commented
exercise 3: The objective is to write into a file some information of the simulation (size, rank coordinate, ..)

comparison between the two tutorials
In initial tutorial:     1) shared data with pdi are considered as data           2)  in sequential
In Yushan tutorial: 1) shared data with pdi are considered as metadata   2)  in // with, one  file by process

I suggest to use the initial tutorial because we can show between data and metadata for the users

2024-11-06 13:27 UTC, jmorice91 commented
> Exercise 1: Yushan have proposed in this exercise
> 
>     * An introduction to paraconf, read the ex1.yml ( perhaps is corresponding to exercise 0  see CMakeLists.txt)
> 
>     * The user need to  add PDI_init and PDI_finalize in ex1.c. => this reason why we have reference of pdi for exercise1 : YAML file, C file and CmakeLists.txt.
> 
> 
> If PDI is linked with paraconf to read the configuration file, I think the first point must be added in the next tutorial.

I have discussed with Yushan and we think that the tutorial must be focus only in PDI.

2024-11-07 15:17 UTC, jbigot requested changes
This is a beginning of review, but I'm not really sure. It would benefit from being split in multiple smaller PRs

2025-01-31 08:39 UTC, closed without merging